package ua.edu.znu.depositcalculator;

// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.ProfilesIni;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;

import static org.junit.jupiter.api.Assertions.assertEquals;

class BrowserProfileSmokeTest {

    private static WebDriver driver;
    private static Map<String, Object> vars;
    private static JavascriptExecutor js;

    @BeforeAll
    public static void setupClass() {
        //Uncomment for Chrome
        //TODO Starts Chrome with user profile, but does not run test -seems updated Chrome version (111.0.5563.147)
        // does not supported by WebDriverManager (but without user profile test runs)
        //Test ignored.
        //org.openqa.selenium.SessionNotCreatedException: Could not start a new session.
        // Response code 500. Message: unknown error: Chrome failed to start:
        // exited normally.
        //  (unknown error: DevToolsActivePort file doesn't exist)
        ChromeOptions options = new ChromeOptions();
        options.addArguments("user-data-dir="+"c:\\Users\\kgp\\AppData\\Local\\Google\\Chrome\\User Data");
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver(options);
        //Uncomment for Firefox
//        ProfilesIni profileini = new ProfilesIni();
//        FirefoxProfile profile = profileini.getProfile("default-release");
//        FirefoxOptions options = new FirefoxOptions();
//        options.setProfile(profile);
//        WebDriverManager.firefoxdriver().setup();
//        driver = new FirefoxDriver(options);

        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
        driver.manage().window().maximize();
    }

    @BeforeEach
    void setUp() {
        driver.get("https://fin-calc.org.ua/ua/deposit/calculate/");
    }

    @AfterAll
    static void tearDownClass() {
        if (driver != null) {
            driver.quit(); // close()
        }
    }

    @Test
    void smokeTest() {
        WebElement sum = driver.findElement(By.id("sum"));
        WebElement term = driver.findElement(By.id("term"));
        WebElement interest = driver.findElement(By.id("percent"));
        sum.clear();
        term.clear();
        interest.clear();
        sum.sendKeys("25000");
        term.sendKeys("12");
        interest.sendKeys("11");
        driver.findElement(By.id("i_scheme5")).click();
        driver.findElement(By.id("submit")).click();

        /*Explicit wait
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(2));
        */

        /*Fluent wait*/
        Wait<WebDriver> wait = new FluentWait<>(driver)
                .withTimeout(Duration.ofSeconds(2))
                .pollingEvery(Duration.ofSeconds(1))
                .ignoring(NoSuchElementException.class);

        WebElement interestAmount = wait.until(ExpectedConditions
                .presenceOfElementLocated(By.cssSelector(".total > .right:nth-child(3)")));
        WebElement sumWithInterest = wait.until(ExpectedConditions
                .presenceOfElementLocated(By.cssSelector(".total > .right:nth-child(4)")));

/*
        String interestAmount = driver.findElement(By.cssSelector(".finale > .right:nth-child(3)")).getText();
        String sumWithInterest = driver.findElement(By.cssSelector(".finale > .right:nth-child(4)")).getText();
*/
        assertEquals("2750.04", interestAmount.getText());
        assertEquals("27750.04", sumWithInterest.getText());
    }
}
