package ua.edu.znu.depositcalculator;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class InitTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public static void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void initTest() {
        driver.get("https://fin-calc.org.ua/ua/deposit/calculate/");
        vars.put("dSum", driver.findElement(By.id("sum")).getAttribute("value"));
        assertEquals(vars.get("dSum").toString(), "25000");
        assertTrue(driver.findElement(By.id("i_scheme5")).isSelected());
        driver.findElement(By.id("submit")).click();
        vars.put("dSumRes", driver.findElement(By.cssSelector(".tresult:nth-child(7) tr:nth-child(2) span")).getText());
        assertEquals(vars.get("dSumRes").toString(), vars.get("dSum").toString());
        System.out.println("Сума депозиту складає " + vars.get("dSum").toString());
    }
}
