package ua.edu.znu.depositcalculator;

// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.slf4j.Logger;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static java.lang.invoke.MethodHandles.lookup;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.slf4j.LoggerFactory.getLogger;

public class SmokeTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public static void setupClass() {
        WebDriverManager.chromedriver().setup();
    }

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void smokeTest() {
        driver.get("https://fin-calc.org.ua/ua/deposit/calculate/");
        WebElement sum = driver.findElement(By.id("sum"));
        WebElement term = driver.findElement(By.id("term"));
        WebElement interest = driver.findElement(By.id("percent"));
        sum.clear();
        term.clear();
        interest.clear();
        sum.sendKeys("25000");
        term.sendKeys("12");
        interest.sendKeys("11");
        driver.findElement(By.id("i_scheme5")).click();
        driver.findElement(By.id("submit")).click();
//        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        String interestAmount = driver.findElement(By.cssSelector(".finale > .right:nth-child(3)")).getText();
        String sumWithInterst = driver.findElement(By.cssSelector(".finale > .right:nth-child(4)")).getText();
        assertEquals("2750.04", interestAmount);
        assertEquals("27750.04", sumWithInterst);
    }
}
